apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: icb1cnqef-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/icb1cnqef-java-quarkus-gitops